December package updates
LibreELEC/LibreELEC.tv pull request #4770
Opened 2020-12-18 00:22 UTC by antonlacon

Couple of bugfix updates I didn't see in the other PRs.

2020-12-19 23:58 UTC, antonlacon commented
zstd bumped to 1.4.8. 1.4.7 had issues on platforms other than x86-64 and aarch64.

2020-12-24 22:50 UTC, heitbaum requested changes
Can you drop mesa, as it is merged in #4786

2020-12-27 09:02 UTC, antonlacon commented
Rebased with tz-2020e

2020-12-27 09:21 UTC, CvH approved these changes

2020-12-27 09:21 UTC, merged