Update rsyslog addon to 8.2012.0 (105) and it’s dependencies
LibreELEC/LibreELEC.tv pull request #4807
Opened 2020-12-28 13:52 UTC by heitbaum

2021-01-06 15:57 UTC, CvH requested changes

2021-01-06 15:57 UTC, CvH commented on packages/addons/addon-depends/rsyslog-depends/libfastjson/package.mk
> +PKG_TOOLCHAIN="configure"
?? configure needed ?

2021-01-06 21:19 UTC, heitbaum commented on packages/addons/addon-depends/rsyslog-depends/libfastjson/package.mk
> +PKG_TOOLCHAIN="configure"
Fixed.

2021-01-07 14:17 UTC, CvH approved these changes

2021-01-07 14:17 UTC, merged