Update packages/graphics current
LibreELEC/LibreELEC.tv pull request #4870
Opened 2021-01-06 10:30 UTC by heitbaum

libprojectM: update to 3.1.8
libepoxy: update to 1.5.5
lcms2: update to 2.11
kmscube: update to HEAD
cairo: update to 1.17.4

2021-01-06 15:51 UTC, CvH requested changes

2021-01-06 15:51 UTC, CvH commented on packages/graphics/lcms2/package.mk
> +PKG_TOOLCHAIN="configure"
??

2021-01-06 15:51 UTC, CvH commented on packages/graphics/libepoxy/package.mk
> +#PKG_URL="https://github.com/anholt/libepoxy/releases/download/${PKG_VERSION}/libepoxy-${PKG_VERSION}.tar.xz"
```suggestion
```

2021-01-06 17:41 UTC, mglae commented
Current visualization.projectm 3.3.0 depend on libprojectM 3.1.7. We should not go ahead without having issues.

2021-01-06 20:05 UTC, CvH commented
3.1.7 -> 3.1.8 includes just 106 commits (:
yea better keep 3.1.7 for now

2021-01-06 22:19 UTC, heitbaum commented on packages/graphics/lcms2/package.mk
> +PKG_TOOLCHAIN="configure"
Fixed.

2021-01-06 22:20 UTC, heitbaum commented
> Current visualization.projectm 3.3.0 depend on libprojectM 3.1.7. We should not go ahead without having issues.

Done. Removed from this pull.

2021-01-07 14:24 UTC, CvH approved these changes

2021-01-07 14:25 UTC, merged