Rockchip: RK3399pro: add initial support for “Radxa ROCK Pi N10”
LibreELEC/LibreELEC.tv pull request #5400
Opened 2021-05-25 13:02 UTC by heitbaum

### DTS
- add the additional dts sections to 
- gpu
- tcs4525 and tcs4526 regulators
- disable the VOP_LIT (Video Output Processor - Little)
- enable i2s2
- enable hdmi_sound
- add gpio/rst/slp
- enable uart2 for serial console

### Patches
- rockchip - regulator: fan53555: Add TCS4525 DCDC support
- Peter Geis
  - regulator: fan53555: fix TCS4525 voltage calulation
  - regulator: fan53555: only bind tcs4525 to correct chip id
  - regulator: fan53555: fix tcs4525 function names
 - @heitbaum - add TCS4526 as used by rk3399pro - vdd_gpu: tcs4526

### Others
- update the uboot_helper to include the additional rock-pi-n10 section
- update release to copy pro files in addition of RK3399
- update README

### Testing
- run tested with LE10b3
- run tested with LE10b3 + 5.10.40-rc1
- run tested with LE10b3 + 5.12.7-rc1

2021-05-26 18:41 UTC, knaerzche requested changes
Looks good - I left some comments.
I'm not a big fan of having patches in devices sub-directories (if not strongly required)  - so could you move the patches to the common RK linux patch directory (if you're not finding a file which matches your needs: create a new one) - and: don't forget to upstream your DT changes :smiley_cat:

2021-05-27 11:07 UTC, heitbaum commented on projects/Rockchip/bootloader/release
> +  cp -a "${SRCDIR}"/${DEVICE,,}{,pro}-*.dtb "${DSTDIR}"
Updated: removed the - from the pattern

2021-05-27 11:47 UTC, heitbaum commented on scripts/uboot_helper
> +        'config': 'rock-pi-n10-rk3399pro_defconfig'
Updated to evb-rk3399_defconfig to match current tree u-boot

2021-05-27 12:32 UTC, heitbaum commented
> Looks good - I left some comments.
> I'm not a big fan of having patches in devices sub-directories (if not strongly required) - so could you move the patches to the common RK linux patch directory (if you're not finding a file which matches your needs: create a new one, but not one per patch, please) - and: don't forget to upstream your DT changes 😺

Have squashed the patches into regulator and dts. Upstreaming my fan53555 patch at the moment. https://lore.kernel.org/lkml/?q=regulator%3A+fan53555

2021-05-27 22:03 UTC, knaerzche commented
Thanks!
One last nit: please also add the board to https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Rockchip/devices/RK3399/README.md

2021-05-28 04:01 UTC, heitbaum commented
> Thanks!
> One last nit: please also add the board to https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Rockchip/devices/RK3399/README.md

Done - Good to go 👍

2021-05-28 16:17 UTC, knaerzche approved these changes

2021-05-28 16:18 UTC, merged