bluez: install empty bluez.pc
LibreELEC/LibreELEC.tv pull request #5957
Opened 2021-12-08 19:39 UTC by jernejsk

bluez.pc is needed to convience pulseaudio that bluez is present. Another alternative would be to enable library, but it's not needed and it would increase size for around 186 KiB on ARM.

2021-12-08 20:19 UTC, lrusak commented
How did you notice this? Did the build fail or does pulseaudio silently continue if it can't find bluez? I would find that odd when bluez is explicitly enabled in pulseaudio.

2021-12-08 20:23 UTC, jernejsk commented
All nightly image builds today failed because pulseaudio couldn't find bluez via pkgconfig (pulseaudio was updated 9h ago). Bluez check was added in pulseaudio 15: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/commit/c817dfb5a438055c98449a4a2f34eb4ec341ccde

2021-12-08 21:01 UTC, lrusak requested changes

2021-12-09 07:27 UTC, chewitt approved these changes

2021-12-09 07:29 UTC, merged