[LE11] dtc: copy libfdt symlink and library
LibreELEC/LibreELEC.tv pull request #6144
Opened 2022-01-17 21:44 UTC by wagnerch

Fixes issues with fdtget/fdtput & "missing" shared library.  Currently only copies libfdt.so symlink (dereferenced), but program is linked against libfdt.so.1.

```sh
# fdtget
fdtget: error while loading shared libraries: libfdt.so.1: cannot open shared object file: No such file or directory
```

2022-01-23 14:10 UTC, CvH requested changes
I would rather not use a asterisk to copy the files, next version could create libtdf.so.123 that would also copied over. Unlikely such additions are recognized at all.

2022-01-23 14:10 UTC, CvH commented on packages/tools/dtc/package.mk
> +    cp -P ${PKG_BUILD}/libfdt/libfdt.so* ${TOOLCHAIN}/lib
```suggestion
    cp -P ${PKG_BUILD}/libfdt/{libfdt.so,libfdt.so.1} ${TOOLCHAIN}/lib
```

2022-01-23 14:10 UTC, CvH commented on packages/tools/dtc/package.mk
> +    cp -P ${PKG_BUILD}/libfdt/libfdt.so* ${INSTALL}/usr/lib/
```suggestion
    cp -P ${PKG_BUILD}/libfdt/{libfdt.so,libfdt.so.1} ${INSTALL}/usr/lib/
```

2022-01-23 14:43 UTC, wagnerch commented on packages/tools/dtc/package.mk
> +    cp -P ${PKG_BUILD}/libfdt/libfdt.so* ${INSTALL}/usr/lib/
Changes have been made.

2022-01-24 19:28 UTC, CvH approved these changes

2022-01-24 19:28 UTC, merged