add full version of less
LibreELEC/LibreELEC.tv pull request #6578
Opened 2022-06-08 02:41 UTC by lrusak

This PR adds the full version of `less` and removes the busybox version.

When dealing with anything that needs a pager (systemctl, journalctl, etc) it's just better to use the full version.

We can also enable use of SYSTEM_COLORS.

2022-06-08 16:25 UTC, CvH requested changes
could you check how big the binary is ?

2022-06-08 16:25 UTC, CvH commented on packages/sysutils/less/package.mk
> +# Copyright (C) 2022 Team LibreELEC (https://libreelec.tv)
```suggestion
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022-present Team LibreELEC (https://libreelec.tv)
```

2022-06-08 16:25 UTC, CvH commented on packages/sysutils/less/package.mk
> +PKG_VERSION="600"
there is 603, both are beta
590 is the "stable" version

2026-08-04 03:15 UTC, chewitt commented
Closing this out due to elapsed time and no action.

2026-08-04 03:15 UTC, closed without merging