[le11] chrome: update to 107.0.5304.87 and addon (114)
LibreELEC/LibreELEC.tv pull request #7101
Opened 2022-11-08 10:07 UTC by heitbaum

- chrome: update to 107.0.5304.87 and addon (114)
- gdk-pixbuf: prevent downloading wrapped subprojects
- gdk-pixbuf: update to 2.42.10
- at-spi2-core: update to 2.46.0 and https
- libXft: update to 2.3.6 and https
- pango: update to 1.50.11

2022-11-08 10:34 UTC, CvH commented
Does chrome extract? Wondering because @SupervisedThinking reported that the deb is not working for him

2022-11-08 10:53 UTC, heitbaum commented
> Does chrome extract? Wondering because @SupervisedThinking reported that the deb is not working for him

I’ll boot both nuc6 and nuc12 into le10 and legacy respectfully in the morning and test. Too busy checking out the blood moon at the moment.

2022-11-20 07:31 UTC, CvH approved these changes

2022-11-20 07:31 UTC, CvH commented
rebase pls

2022-11-26 17:42 UTC, SupervisedThinking commented
@heitbaum did you test the tar / xz extraction?

2022-11-29 18:31 UTC, mglae commented
@SupervisedThinking Can confirm extraction error. Recent Google chrome deb files do have two issues for us:

1. The ar archive contains illegal file mode 644 instead of 100644. Busybox ar is refusing this.
2. The xz/lzma compression is using CRC64. Busybox only implements CRC32.

@heitbaum Please include https://github.com/mglae/LibreELEC.tv/commits/le11_chrome_114_download

2022-11-29 19:16 UTC, SupervisedThinking commented
@mglae how about
shipping binutils ar:
- https://github.com/SupervisedThinking/LibreELEC-RR/commit/241dd61733d45040317c22c54574d65a7f08e0f7
- https://github.com/SupervisedThinking/LibreELEC-RR/commit/e93db4d2435dad9ab4aad35691d4833c626af380

using xz binary instead binutils xz
- https://github.com/SupervisedThinking/LibreELEC-RR/commit/9286e50c08ef297de72f9b1867cde2ecd7634af3
- https://github.com/SupervisedThinking/LibreELEC-RR/commit/09cacf7d5b3a641339623e3b24ba6ddba68090fd

use xz & ar for the deb files
- https://github.com/SupervisedThinking/LibreELEC-RR/blob/master-rr/packages/supervisedthinking/web/brave-browser/scripts/brave-browser.start#L97-L99

= we don't need new packages & just use already build stuff

2022-11-29 19:20 UTC, CvH commented
isn't z7ip supporting it too ?
also we can switch from legacy p7zip to 7zip these days too

2022-11-29 22:36 UTC, mglae commented
@SupervisedThinking With backport in mind I decided to only change the addon and not the image. But if wanted the needed binaries can be added to the addon and called with absolute path.

2022-12-02 19:14 UTC, SupervisedThinking commented
@mglae that's indeed a point... anyway mind to report your findings at https://bugs.busybox.net/ ?

2022-12-04 18:02 UTC, mglae commented
@SupervisedThinking No. The behavior is bad for us but I don't see an error.

1. Busybox implements an archiver for the ar format whereas binutils ar "only" seem to be working with regular files in static libs.
2. xz behavior fulfil the [xz file format documentation](https://git.tukaani.org/?p=xz.git;a=blob;f=doc/xz-file-format.txt;h=4ed665060183375b8a1fb74384d01636042b1bcf;hb=24790f49ae66938c1c7574315e1c0aba1ed5ed25#l353). CRC64 is optional.

2022-12-10 19:44 UTC, SupervisedThinking commented
I guess since https://github.com/LibreELEC/LibreELEC.tv/pull/7106 was merged we should check which xorg libs we need to rebuild

2022-12-10 22:26 UTC, heitbaum commented
> I guess since #7106 was merged we should check which xorg libs we need to rebuild

I have rebased this. But next will be which chrome- libraries should be dropped

2022-12-10 23:13 UTC, SupervisedThinking commented
IMHO all which where now build shared, we don't need to ship them for chrome once they are included anyway

2023-01-10 23:37 UTC, heitbaum commented
Hi @mglae / @antonlacon - commit pulled in - and this PR "MERGE BLOCK" dropped.

2023-01-11 06:56 UTC, heitbaum commented
> I believe this needs mglae's commits to replace the *.deb extraction with python from: https://github.com/mglae/LibreELEC.tv/commits/le11_chrome_114_download

Added. With a minor typographic fix in ad7e849945f21100302c87dbc5050f2a8a42eb0c

2023-01-11 17:51 UTC, mglae commented
Working fine (read: chrome is starting) but being coauthor I cannot approve.

2023-01-11 19:34 UTC, CvH requested changes

2023-01-11 19:34 UTC, CvH commented on packages/addons/addon-depends/chrome-depends/unix_ar/package.mk
> +# SPDX-License-Identifier: GPL-2.0
```suggestion
# SPDX-License-Identifier: GPL-2.0-only
```

2023-01-11 21:30 UTC, heitbaum commented on packages/addons/addon-depends/chrome-depends/unix_ar/package.mk
> +PKG_DEPENDS_TARGET=""
updated and squashed

2023-01-11 21:30 UTC, heitbaum commented on packages/addons/addon-depends/chrome-depends/unix_ar/package.mk
> +# SPDX-License-Identifier: GPL-2.0
updated and squashed

2023-01-11 21:31 UTC, heitbaum commented on packages/addons/browser/chrome/source/bin/deb_extract_data
> +# SPDX-License-Identifier: GPL-2.0
updated and squashed

2023-01-12 19:21 UTC, CvH approved these changes

2023-01-12 19:21 UTC, merged