[le12] system-tools: replace dstat with dool and updates and addon (1)n
LibreELEC/LibreELEC.tv pull request #7981
Opened 2023-07-14 13:46 UTC by heitbaum

- bottom: update to 0.9.3
- diffutils: update to 3.10
- dool: initial package
- dstat: drop package
- libssh2: update to 1.11.0
- stress-ng: update to 0.16.01
- unrar: update to 6.2.8

2023-07-14 19:45 UTC, CvH requested changes

2023-07-14 19:45 UTC, CvH commented on packages/addons/addon-depends/system-tools-depends/dool/package.mk
> +PKG_VERSION="1.1.0"
https://github.com/scottchiefbaker/dool/releases/tag/v1.2.0 (:

2023-07-15 00:57 UTC, heitbaum commented on packages/addons/addon-depends/system-tools-depends/dool/package.mk
> +PKG_VERSION="1.1.0"
Updated 👍

2023-07-15 08:08 UTC, CvH approved these changes

2023-07-15 08:08 UTC, merged